[package]
name = "Course-kudasai"
version = "0.0.1"
edition = "2021"


[package.metadata.winresource]
OriginalFilename = "選課小幫手.exe"
LegalCopyright = "Copyright © 2024 NTUST-Tool"

[dependencies]
reqwest = { version = "0.13.5", default-features = false, features = ["json", "native-tls"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "time"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
rust-ini = "0.21"

[build-dependencies]
winresource = "0.1.31"

[[bin]]
name = "Course-kudasai"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"